services:
  httpd:
    container_name: stats-web
    image: 'httpd:2.4'
    ports:
      - '8080:80'
    volumes:
      - './frontend:/usr/local/apache2/htdocs/'
      - './data-collection:/opt/data-collection'
    