services:
  httpd_container:
    container_name: stats-web
    image: httpd:2.4
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
      - httpd_docs:/usr/local/apache2/htdocs/  # Shared volume
      #Shared volume should only be used for data, which means separate subfolder which means refactor structure
    # Note: httpd-foreground below lets the web server keep running. Otherwise the container just exits
    command: httpd-foreground

  cron_container:
    container_name: dataCollector
    image: alpine
    volumes:
      - httpd_docs:/httpd_docs  # This shares the same volume
      - ./data-collection:/opt/data-collection
    command: sh -c "chmod u+x /opt/data-collection/dataCollection.sh &&
                    cp /opt/data-collection/dataCollectionCron /etc/crontabs/root &&
                    /opt/data-collection/dataCollection.sh /httpd_docs &&
                    crond -f"
volumes:
  httpd_docs:
